# Docker compose project for Virtual Temperature Sensor Adapter
#
# Deploy the virtual adapter:
#   docker compose up -d
#
# Tear down the virtual adapter
#   docker compose down

services:
  virtual-temperature-sensor-adapter:
    build:
      context: .
      dockerfile: Dockerfile
    image: ofa/vtempsens
    environment:
      - SLEEP_INTERVAL=2.0
      - MIN_TEMP=19
      - MAX_TEMP=21
      - ADAPTER_PORT=7878
    ports:
      - "7878:7878"
    networks:
      - factory-net

networks:

  factory-net:
    name: factory-net
    external: true
