name: Kafka Partitioning Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get Host IP
      - name: Get Host IP
        id: get_ip
        run: |
          echo "HOST_IP=$(hostname -I | awk '{print $1}')" >> $GITHUB_ENV
          echo "Host IP is $HOST_IP"

      # Step 2: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Step 6: Run Kafka with Docker
      - name: Run Kafka with Docker
        run: |
          docker-compose -f docker-compose.yml up -d

      # Step 7: Wait for Kafka to be ready
      - name: Wait for Kafka to be ready
        run: |
          for i in {1..30}; do
            if nc -zv ${HOST_IP} 9092; then
              echo "Kafka is ready!"
              break
            else
              echo "Waiting for Kafka to be ready... ($i)"
              sleep 5
            fi
          done

      # Step 8: Run Kafka Partitioning Test
      - name: Run Kafka Partitioning Test
        run: python -m unittest discover tests

      # Step 9: Shutdown Kafka
      - name: Shutdown Kafka
        run: docker-compose down
