name: Kafka Partitioning Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      broker:
        image: confluentinc/cp-kafka:7.7.0
        ports:
          - 9092:9092
          - 9101:9101
        options: >-
          --add-host=host.docker.internal:host-gateway
          --env KAFKA_NODE_ID=1
          --env KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
          --env KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://broker:29092,PLAINTEXT_HOST://host.docker.internal:9092"
          --env KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
          --env KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
          --env KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
          --env KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
          --env KAFKA_PROCESS_ROLES="broker,controller"
          --env KAFKA_CONTROLLER_QUORUM_VOTERS="1@broker:29093"
          --env KAFKA_LISTENERS="PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092"
          --env KAFKA_INTER_BROKER_LISTENER_NAME="PLAINTEXT"
          --env KAFKA_CONTROLLER_LISTENER_NAMES="CONTROLLER"
          --env KAFKA_LOG_DIRS="/tmp/kraft-combined-logs"
          --env CLUSTER_ID="MkU3OEVBNTcwNTJENDM2QkhjfdKKFDdSML"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Kafka to be ready
        run: |
          for i in {1..30}; do
            if nc -zv broker 9092; then
              echo "Kafka is ready!"
              break
            else
              echo "Waiting for Kafka to be ready... ($i)"
              sleep 5
            fi
          done

      - name: Run Kafka Partitioning Test
        run: python -m unittest discover tests

      - name: Shutdown Kafka
        run: docker stop broker
